// =============================================================
// codegen.js — C code generation from FSM graph
// =============================================================

function toEnumName(label) {
    return label
        .replace(/[^a-zA-Z0-9_]/g, '_')
        .replace(/^(\d)/, '_$1')
        .toUpperCase();
}

function parseEventNames(transitionLabel) {
    return transitionLabel.split('[')[0].split(',').map(e => e.trim()).filter(e => e);
}

function resolvePseudoChain(pseudo) {
    const outgoing = transitions.filter(t => t.from === pseudo);
    const branches = [];
    outgoing.forEach(t => {
        const condRaw = t.label.trim();
        const cond = condRaw && !condRaw.startsWith('[') ? `[${condRaw}]` : condRaw;
        if (t.to.isPseudostate) {
            const sub = resolvePseudoChain(t.to);
            sub.forEach(b => branches.push({
                cond: cond ? `${cond} && ${b.cond}` : b.cond,
                target: b.target, action: [t.action, b.action].filter(Boolean).join('\n')
            }));
        } else {
            branches.push({ cond, target: t.to, action: t.action });
        }
    });
    return branches;
}

function generateCCode() {
    const codePanel = document.getElementById('codePanel');
    const codeOutput = document.getElementById('codeOutput');
    const toolbar = document.getElementById('toolbar');

    if (!codePanel.classList.contains('hidden')) {
        codePanel.classList.add('hidden');
        return;
    }

    const tbRect = toolbar.getBoundingClientRect();
    codePanel.style.top = (tbRect.bottom + 10) + 'px';

    const realStates = states.filter(s => !s.isPseudostate);

    if (realStates.length === 0) {
        codeOutput.textContent = '/* No states defined yet. */';
        codePanel.classList.remove('hidden');
        return;
    }

    // Collect unique events
    const eventSet = new Set();
    transitions.forEach(t => {
        if (!t.from.isPseudostate) {
            t.label.split('\n').forEach(lbl => {
                const evtNames = parseEventNames(lbl.trim());
                evtNames.forEach(e => eventSet.add(e));
            });
        }
    });
    const events = [...eventSet];

    const lines = [];
    lines.push('/* Auto-generated by FSM Grapher */');
    lines.push('#include <stdint.h>');
    lines.push('');

    // State enum
    lines.push('/* States */');
    lines.push('typedef enum {');
    realStates.forEach((s, i) => {
        lines.push(`    STATE_${toEnumName(s.label)}${i < realStates.length - 1 ? ',' : ''}`);
    });
    lines.push('} FSMState;');
    lines.push('');

    // Event enum
    if (events.length > 0) {
        lines.push('/* Events */');
        lines.push('typedef enum {');
        events.forEach((e, i) => {
            lines.push(`    EVENT_${toEnumName(e)}${i < events.length - 1 ? ',' : ''}`);
        });
        lines.push('} FSMEvent;');
        lines.push('');
    }

    // fsm_process_event
    lines.push('/* Process event and execute actions */');
    lines.push('FSMState fsm_process_event(FSMState current, FSMEvent event) {');
    lines.push('    FSMState next = current;');
    lines.push('    switch (current) {');
    realStates.forEach(s => {
        const outgoing = transitions.filter(t => t.from === s);
        if (!outgoing.length) return;
        lines.push(`        case STATE_${toEnumName(s.label)}:`);
        outgoing.forEach(t => {
            const lblLines = t.label.split('\n').map(l => l.trim()).filter(Boolean);
            if (t.to.isPseudostate) {
                const branches = resolvePseudoChain(t.to);
                lblLines.forEach(lbl => {
                    const evtNames = parseEventNames(lbl);
                    if (!evtNames.length) return;
                    const condPart = lbl.includes('[') ? lbl.substring(lbl.indexOf('[')) : '';
                    evtNames.forEach(evtName => {
                        lines.push(`            if (event == EVENT_${toEnumName(evtName)}) {`);
                        branches.forEach(b => {
                            const fullCond = [condPart, b.cond].filter(Boolean).join(' && ')
                                .replace(/\[/g, '(').replace(/\]/g, ')');
                            if (fullCond) {
                                lines.push(`                if (${fullCond}) {`);
                            } else {
                                lines.push(`                {`);
                            }

                            if (t.action) {
                                t.action.split('\n').forEach(a => { if (a.trim()) lines.push(`                    ${a.trim()};`); });
                            }
                            if (b.action) {
                                b.action.split('\n').forEach(a => { if (a.trim()) lines.push(`                    ${a.trim()};`); });
                            }

                            lines.push(`                    next = STATE_${toEnumName(b.target.label)};`);
                            lines.push(`                    break;`);
                            lines.push(`                }`);
                        });
                        lines.push(`            }`);
                    });
                });
            } else {
                lblLines.forEach(lbl => {
                    const evtNames = parseEventNames(lbl);
                    if (!evtNames.length) return;
                    const condPart = lbl.includes('[') ? lbl.substring(lbl.indexOf('[')).replace(/\[/g, '(').replace(/\]/g, ')') : '';
                    evtNames.forEach(evtName => {
                        if (condPart) {
                            lines.push(`            if (event == EVENT_${toEnumName(evtName)} && ${condPart}) {`);
                        } else {
                            lines.push(`            if (event == EVENT_${toEnumName(evtName)}) {`);
                        }
                        if (t.action) {
                            t.action.split('\n').forEach(a => { if (a.trim()) lines.push(`                ${a.trim()};`); });
                        }
                        lines.push(`                next = STATE_${toEnumName(t.to.label)};`);
                        lines.push(`                break;`);
                        lines.push(`            }`);
                    });
                });
            }
        });
        lines.push(`            break;`);
    });
    lines.push('        default: break;');
    lines.push('    }');

    // Entry actions
    lines.push('');
    lines.push('    if (next != current) {');
    const statesWithActions = realStates.filter(s => s.action && s.action.trim());
    if (statesWithActions.length > 0) {
        lines.push('        switch (next) {');
        statesWithActions.forEach(s => {
            lines.push(`            case STATE_${toEnumName(s.label)}:`);
            s.action.split('\n').forEach(a => { if (a.trim()) lines.push(`                ${a.trim()};`); });
            lines.push(`                break;`);
        });
        lines.push('            default: break;');
        lines.push('        }');
    }
    lines.push('    }');
    lines.push('    return next;');
    lines.push('}');

    const startObj = states.find(s => s.isStart);
    if (startObj) {
        lines.push('');
        lines.push('/* Initialize FSM */');
        lines.push('FSMState fsm_init(void) {');
        lines.push(`    FSMState initial = STATE_${toEnumName(startObj.label)};`);
        if (startObj.startAction) {
            startObj.startAction.split('\n').forEach(a => { if (a.trim()) lines.push(`    ${a.trim()};`); });
        }
        if (startObj.action) {
            startObj.action.split('\n').forEach(a => { if (a.trim()) lines.push(`    ${a.trim()};`); });
        }
        lines.push('    return initial;');
        lines.push('}');
    }

    codeOutput.textContent = lines.join('\n');
    codePanel.classList.remove('hidden');
}
