// =============================================================
// codegen.js — C code generation from FSM graph
// =============================================================

function toEnumName(label) {
    return label
        .replace(/[^a-zA-Z0-9_]/g, '_')
        .replace(/^(\d)/, '_$1')
        .toUpperCase();
}

function parseEventName(transitionLabel) {
    return transitionLabel.split('[')[0].trim();
}

function resolvePseudoChain(pseudo) {
    const outgoing = transitions.filter(t => t.from === pseudo);
    const branches = [];
    outgoing.forEach(t => {
        const condRaw = t.label.trim();
        const cond = condRaw && !condRaw.startsWith('[') ? `[${condRaw}]` : condRaw;
        if (t.to.isPseudostate) {
            const sub = resolvePseudoChain(t.to);
            sub.forEach(b => branches.push({
                cond: cond ? `${cond} && ${b.cond}` : b.cond,
                target: b.target, action: t.action || b.action
            }));
        } else {
            branches.push({ cond, target: t.to, action: t.action });
        }
    });
    return branches;
}

function generateCCode() {
    const codePanel = document.getElementById('codePanel');
    const codeOutput = document.getElementById('codeOutput');
    const toolbar = document.getElementById('toolbar');

    if (!codePanel.classList.contains('hidden')) {
        codePanel.classList.add('hidden');
        return;
    }

    const tbRect = toolbar.getBoundingClientRect();
    codePanel.style.top = (tbRect.bottom + 10) + 'px';

    const realStates = states.filter(s => !s.isPseudostate);

    if (realStates.length === 0) {
        codeOutput.textContent = '/* No states defined yet. */';
        codePanel.classList.remove('hidden');
        return;
    }

    // Collect unique events
    const eventSet = new Set();
    transitions.forEach(t => {
        if (!t.from.isPseudostate) {
            t.label.split('\n').forEach(lbl => {
                const evtName = parseEventName(lbl.trim());
                if (evtName) eventSet.add(evtName);
            });
        }
    });
    const events = [...eventSet];

    const lines = [];
    lines.push('/* Auto-generated by FSM Grapher */');
    lines.push('#include <stdint.h>');
    lines.push('');

    // State enum
    lines.push('/* States */');
    lines.push('typedef enum {');
    realStates.forEach((s, i) => {
        lines.push(`    STATE_${toEnumName(s.label)}${i < realStates.length - 1 ? ',' : ''}`);
    });
    lines.push('} FSMState;');
    lines.push('');

    // Event enum
    if (events.length > 0) {
        lines.push('/* Events */');
        lines.push('typedef enum {');
        events.forEach((e, i) => {
            lines.push(`    EVENT_${toEnumName(e)}${i < events.length - 1 ? ',' : ''}`);
        });
        lines.push('} FSMEvent;');
        lines.push('');
    }

    // fsm_next_state
    lines.push('/* Transition table */');
    lines.push('FSMState fsm_next_state(FSMState current, FSMEvent event) {');
    lines.push('    switch (current) {');
    realStates.forEach(s => {
        const outgoing = transitions.filter(t => t.from === s);
        if (!outgoing.length) return;
        lines.push(`        case STATE_${toEnumName(s.label)}:`);
        outgoing.forEach(t => {
            const lblLines = t.label.split('\n').map(l => l.trim()).filter(Boolean);
            if (t.to.isPseudostate) {
                const branches = resolvePseudoChain(t.to);
                lblLines.forEach(lbl => {
                    const evtName = parseEventName(lbl);
                    if (!evtName) return;
                    const condPart = lbl.includes('[') ? lbl.substring(lbl.indexOf('[')) : '';
                    lines.push(`            if (event == EVENT_${toEnumName(evtName)}) {`);
                    branches.forEach(b => {
                        const fullCond = [condPart, b.cond].filter(Boolean).join(' && ')
                            .replace(/\[/g, '(').replace(/\]/g, ')');
                        if (fullCond) {
                            lines.push(`                if (${fullCond}) return STATE_${toEnumName(b.target.label)};`);
                        } else {
                            lines.push(`                return STATE_${toEnumName(b.target.label)};`);
                        }
                    });
                    lines.push(`            }`);
                });
            } else {
                lblLines.forEach(lbl => {
                    const evtName = parseEventName(lbl);
                    if (!evtName) return;
                    const condPart = lbl.includes('[') ? lbl.substring(lbl.indexOf('[')).replace(/\[/g, '(').replace(/\]/g, ')') : '';
                    if (condPart) {
                        lines.push(`            if (event == EVENT_${toEnumName(evtName)} && ${condPart}) return STATE_${toEnumName(t.to.label)};`);
                    } else {
                        lines.push(`            if (event == EVENT_${toEnumName(evtName)}) return STATE_${toEnumName(t.to.label)};`);
                    }
                });
            }
        });
        lines.push(`            break;`);
    });
    lines.push('        default: break;');
    lines.push('    }');
    lines.push('    return current; /* No matching transition */');
    lines.push('}');
    lines.push('');

    // fsm_entry_action
    const statesWithActions = realStates.filter(s => s.action && s.action.trim());
    lines.push('/* Entry actions */');
    lines.push('void fsm_entry_action(FSMState state) {');
    if (statesWithActions.length > 0) {
        lines.push('    switch (state) {');
        statesWithActions.forEach(s => {
            lines.push(`        case STATE_${toEnumName(s.label)}:`);
            s.action.split('\n').forEach(a => { if (a.trim()) lines.push(`            ${a.trim()};`); });
            lines.push(`            break;`);
        });
        lines.push('        default: break;');
        lines.push('    }');
    }
    lines.push('}');
    lines.push('');

    // fsm_run_action
    const transWithActions = transitions.filter(t => !t.from.isPseudostate && t.action && t.action.trim());
    lines.push('/* Transition actions */');
    lines.push('void fsm_run_action(FSMState from, FSMEvent event, FSMState to) {');
    if (transWithActions.length > 0) {
        lines.push('    (void)event;');
        transWithActions.forEach(t => {
            lines.push(`    if (from == STATE_${toEnumName(t.from.label)} && to == STATE_${toEnumName(t.to.label)}) {`);
            t.action.split('\n').forEach(a => { if (a.trim()) lines.push(`        ${a.trim()};`); });
            lines.push(`    }`);
        });
    } else {
        lines.push('    (void)from; (void)event; (void)to;');
    }
    lines.push('}');

    codeOutput.textContent = lines.join('\n');
    codePanel.classList.remove('hidden');
}
